[package]
name = "rust-device-reading"
version = "0.1.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]

[dependencies]
jack = "*"
galvanic-test = "*"
evdev-rs = { git = "https://github.com/ndesh26/evdev-rs", rev = "c271060" }
sdl = "*"
palette = "*"
