[package]
name = "dev"
version = "0.1.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]

[dependencies]
jack = "*"
galvanic-test = "*"
evdev-rs = { git = "https://github.com/soenkehahn/evdev-rs", rev = "97ff0b0" }
